# Generated by Django 4.2.5 on 2023-10-20 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LectureRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCell',
            fields=[
                ('schedule_cell', models.AutoField(primary_key=True, serialize=False)),
                ('cell_content', models.TextField(default='')),
                ('border', models.CharField(default='1px solid #DDD', max_length=255)),
                ('background_color', models.CharField(default='white', max_length=255)),
                ('colspan_st', models.IntegerField(default=1)),
                ('rowspan_st', models.IntegerField(default=1)),
                ('colspan_en', models.IntegerField(default=1)),
                ('rowspan_en', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2023)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.TimeField()),
                ('memo_content', models.TextField(blank=True, null=True)),
                ('lecture_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.lectureroom')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('color', models.CharField(default='#000000', max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(default=2, max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(default='')),
                ('year', models.IntegerField(default=2023)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.TimeField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.lectureroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('year', 'day', 'month', 'time', 'user_id')},
            },
        ),
    ]
