# Generated by Django 4.2.5 on 2023-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_user_updatecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecell',
            name='color',
            field=models.CharField(default='#0000000', max_length=10),
        ),
    ]
