# Generated by Django 4.2.5 on 2023-10-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ScheduleCell',
            fields=[
                ('schedule_cell', models.AutoField(primary_key=True, serialize=False)),
                ('cell_content', models.TextField()),
                ('border', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=255)),
                ('colspan_st', models.IntegerField(default=1)),
                ('rowspan_st', models.IntegerField(default=1)),
                ('colspan_en', models.IntegerField(default=1)),
                ('rowspan_en', models.IntegerField(default=1)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.TimeField()),
                ('memo_content', models.TextField(blank=True, null=True)),
                ('lecture_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.lectureroom')),
            ],
        ),
    ]
