# Generated by Django 4.2.5 on 2023-10-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_alter_schedule_task_description_schedulecell'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecell',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='schedulecell',
            name='background_color',
            field=models.CharField(default='white', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulecell',
            name='border',
            field=models.CharField(default='1px solid #DDD', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulecell',
            name='cell_content',
            field=models.TextField(default=''),
        ),
    ]
