# Generated by Django 4.2.5 on 2023-10-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_schedulecell_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
