# Generated by Django 4.2.5 on 2023-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_remove_schedule_end_time_remove_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=2, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user_id', 'day', 'month', 'time')},
        ),
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
