# Generated by Django 4.2.5 on 2023-10-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_alter_schedule_day_alter_schedule_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('year', 'day', 'month', 'time', 'user_id')},
        ),
    ]
